name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          docker build -t ${{ secrets.ECR_REPOSITORY }}:appointment-service-$IMAGE_TAG . -f appointment-service-dockerfile
          docker build -t ${{ secrets.ECR_REPOSITORY }}:patient-service-$IMAGE_TAG . -f patient-service-dockerfile
          docker images


      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:appointment-service-$IMAGE_TAG
          docker push ${{ secrets.ECR_REPOSITORY }}:patient-service-$IMAGE_TAG
